xyz-system-api:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  springdoc:
    swagger-ui:
      enabled: true

  oidc:
    host: ${KC_HOST}
    client-id: ${KC_CLIENT_ID}
    realm: ${KC_REALM}
    issuer-uri: ${KC_HOST}/realms/${KC_REALM}
    jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

  openapi-servers-urls: http://localhost:${server.port}${server.servlet.context-path}, http://127.0.0.1:${server.port}${server.servlet.context-path}